---
generic-service:
  nameOverride: hmpps-it-incident-hub

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-it-incident-hub
    tag: app_version    # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: hmpps-it-incident-hub-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  custommetrics:
    enabled: true
    scrapeInterval: 15s
    metricsPath: /metrics
    metricsPort: 3001

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    SERVICENOW_CONTACT_TYPE: "Atos Auto-Ticketing"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-it-incident-hub:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
      SESSION_SECRET: "SESSION_SECRET"
      SERVICENOW_CALLER_ID: "SERVICENOW_CALLER_ID"
      SERVICENOW_DEPT_ID: "SERVICENOW_DEPT_ID"
      SERVICENOW_CONFIG_ITEM: "SERVICENOW_CONFIG_ITEM"
      SERVICENOW_SERVICE_OFFERING: "SERVICENOW_SERVICE_OFFERING"
      SERVICENOW_ASSIGNMENT_GROUP: "SERVICENOW_ASSIGNMENT_GROUP"
      SERVICENOW_USER: "SERVICENOW_USER"
      SERVICENOW_PASS: "SERVICENOW_PASS"

    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    petty-france-wifi: "213.121.161.112/28"
    global-protect: "35.176.93.186/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"
    ark-dom1-psn1: 51.247.4.0/24
    ark-dom1-psn2: 51.247.3.0/24
    ark-nps-hmcts-ttp1: 195.59.75.0/24
    ark-nps-hmcts-ttp2: 194.33.192.0/25
    ark-nps-hmcts-ttp3: 194.33.193.0/25
    ark-nps-hmcts-ttp4: 194.33.196.0/25
    ark-nps-hmcts-ttp5: 194.33.197.0/25
    dxc_webproxy1: 195.92.38.20/32
    dxc_webproxy2: 195.92.38.21/32
    dxc_webproxy3: 195.92.38.22/32
    dxc_webproxy4: 195.92.38.23/32
    moj-official-tgw-preprod: 51.149.251.0/24
    moj-official-tgw-prod: 51.149.250.0/24
    moj-official-ark-c-expo-e: 51.149.249.0/29
    moj-official-ark-c-vodafone: 194.33.248.0/29
    moj-official-ark-f-vodafone: 194.33.249.0/29
    moj-official-ark-f-expo-e: 51.149.249.32/29
    ext-digital-accessibility-centre: 194.75.245.154/32

generic-prometheus-alerts:
  targetApplication: hmpps-it-incident-hub
