generic-service:
  nameOverride: hmpps-it-incident-hub

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-it-incident-hub
    tag: app_version # override at deployment time
    port: 3000

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-it-incident-hub-cert

  livenessProbe:
    httpGet:
      path: /ping

  readinessProbe:
    httpGet:
      path: /ping

  custommetrics:
    enabled: true
    scrapeInterval: 15s
    metricsPath: /metrics
    metricsPort: 3001

  # Environment variables to load into the deployment
  env:
    NODE_ENV: "production"
    REDIS_TLS_ENABLED: "true"
    TOKEN_VERIFICATION_ENABLED: "true"
    SERVICENOW_CONTACT_TYPE: "Atos Auto-Ticketing"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY);IngestionEndpoint=https://northeurope-0.in.applicationinsights.azure.com/;LiveEndpoint=https://northeurope.livediagnostics.monitor.azure.com/"

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-it-incident-hub:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"
      SYSTEM_CLIENT_ID: "SYSTEM_CLIENT_ID"
      SYSTEM_CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
      SESSION_SECRET: "SESSION_SECRET"
      SERVICENOW_CALLER_ID: "SERVICENOW_CALLER_ID"
      SERVICENOW_DEPT_ID: "SERVICENOW_DEPT_ID"
      SERVICENOW_CONFIG_ITEM: "SERVICENOW_CONFIG_ITEM"
      SERVICENOW_SERVICE_OFFERING: "SERVICENOW_SERVICE_OFFERING"
      SERVICENOW_ASSIGNMENT_GROUP: "SERVICENOW_ASSIGNMENT_GROUP"
      SERVICENOW_USER: "SERVICENOW_USER"
      SERVICENOW_PASS: "SERVICENOW_PASS"

    elasticache-redis:
      REDIS_HOST: "primary_endpoint_address"
      REDIS_AUTH_TOKEN: "auth_token"

  allowlist:
    ark-dom1-farnborough: 194.33.192.0/24
    ark-dom1-corsham: 194.33.196.0/24
    ext-digital-accessibility-centre: 194.75.245.154/32
    groups:
      - internal
      - prisons

generic-prometheus-alerts:
  targetApplication: hmpps-it-incident-hub
