---
# Per environment values which override defaults in hmpps-it-incident-hub/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: it-incident-hub.hmpps.service.justice.gov.uk
    contextColour: green
    v1_2_enabled: true
    v0_47_enabled: false

  env:
    INGRESS_URL: "https://it-incident-hub.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    SERVICENOW_API_URL: "https://mojprod.service-now.com/"

generic-prometheus-alerts:
  alertSeverity: digital-prison-service

